version: '3.8'

services:
  db:
    image: mysql:8.0.22
    container_name: agile-diary-db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-dump/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somesecret
      MYSQL_DATABASE: agileDiary
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

  adminer:
    image: adminer
    container_name: agile-diary-db-admin
    restart: always
    ports:
      - 8080:8080
  # todo: fix Dockerfile
#  javafx:
#    build:
#      context: src
#      dockerfile: Dockerfile
#    depends_on:
#      - db

volumes:
  mysql-dump: {}